### ISSUE TITLE
Error on Run

### ISSUE THREAD

**Issue by archaik** [loewens/fox2chrome-tags#1]
Hi, do you know what could be going on here?

When I run the script, I get this error:

Error: Could not find or load main class FirefoxToChrome

**Comment by saladpanda** [comment]
Did you compile the FirefoxToChrome.java first?

`javac FirefoxToChrome.java`

**Comment by archaik** [comment]
Thank you, no, I had not yet. When I run 'javac FirefoxToChrome.java', these messages come up:

Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Then, when I run 'javac FirefoxToChrome.java bookmarks.json bookmarks.html', this message shows:

Exception in thread "main" java.lang.NullPointerException
    at FirefoxToChrome.extractPlaces(FirefoxToChrome.java:33)
    at FirefoxToChrome.extractPlaces(FirefoxToChrome.java:34)
    at FirefoxToChrome.main(FirefoxToChrome.java:20)

**Comment by saladpanda** [comment]
Should be fixed. Try again, please.

**Comment by archaik** [comment]
Thank you, it now creates an html file, but with empty arrays at the end of each link '[]'. I checked my json input file; it has tags.

**Comment by saladpanda** [comment]
Can you give me a minimal example-json? I'm currently short on time.

**Comment by archaik** [comment]
here you go:

``` json
{
  "lastModified": 1453938387410000,
  "root": "placesRoot",
  "id": 1,
  "children": [
    {
      "lastModified": 1418454435326000,
      "id": 8659,
      "title": "",
      "dateAdded": 1416590041485000,
      "type": "text/x-moz-place-container",
      "guid": "L7DoGBeK_U9j",
      "index": 0
    },
    {
      "lastModified": 1453955407906000,
      "root": "bookmarksMenuFolder",
      "id": 2,
      "children": [
        {
          "lastModified": 1453398829486000,
          "id": 8693,
          "children": [
            {
              "lastModified": 1440200793266000,
              "uri": "https://stackexchange.com/sites#",
              "id": 167,
              "charset": "UTF-8",
              "title": "All Sites - Stack Exchange",
              "dateAdded": 1386371288791000,
              "iconuri": "https://stackexchange.com/favicon.ico",
              "type": "text/x-moz-place",
              "guid": "wzZytWHpz5GA",
              "tags": "answers,forum,stack exchange,web",
              "index": 0
            },
            {
              "lastModified": 1440200793310000,
              "uri": "https://security.stackexchange.com/",
              "id": 16,
              "iconuri": "https://cdn.sstatic.net/security/img/favicon.ico?v=f7361b03b1a9",
              "title": "Stack Exchange. Info Security",
              "dateAdded": 1386314514457000,
              "type": "text/x-moz-place",
              "guid": "dES65G0O6k9x",
              "tags": "forum,stack exchange",
              "index": 5
            },
            {
              "lastModified": 1440200793317000,
              "uri": "http://programmers.stackexchange.com/",
              "id": 158,
              "charset": "UTF-8",
              "title": "Stack Exchange. Programmers",
              "dateAdded": 1372378396000000,
              "iconuri": "https://cdn.sstatic.net/programmers/img/favicon.ico?v=8fef1c85f782",
              "type": "text/x-moz-place",
              "guid": "e1I1tfcHnrNJ",
              "tags": "answers,computer science,forum,programming,stack exchange",
              "index": 6
            },
```

**Comment by saladpanda** [comment]
It seems like they changed the format of the json-backup since I wrote this little tool 2years ago.
I adjusted it to the new format. Please try again.
